variables:
  BINARY_NAME: $CI_PROJECT_NAME

stages: 
 - build

build:
  stage: build
  image: golang:alpine3.6
  script:
    - go get github.com/golang/dep/cmd/dep
    - dep ensure
    - mkdir build
    - go build -o build/policyd