// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package db

import (
	"database/sql"
	"time"
)

type Event struct {
	Ts             time.Time
	SaslUsername   string
	Sender         string
	ClientAddress  string
	RecipientCount sql.NullInt32
}
